### ISSUE TITLE
php box.phar build  This command is not working

### ISSUE THREAD

**Issue by flik** [box-project/box2-example#1]
I have downloaded the box2-example and when I run the command php box.phar build 
I am getting this message.
Could not open input file: box.phar

**Comment by diazwatson** [comment]
This issue seems a bit old but if you still have problems, try adding execute permissions to .phar file like this:
`chmod +x box.phar`

Hope it helps

**Comment by kherge** [comment]
Hey @flik, you receive that error message when you don't have `box.phar` in the current working directory path. I suggest that you [install Box using the instructions here](https://github.com/box-project/box2#as-a-phar-recommended).
